title: Mads Bønding
description: Data enthusiast and useR trying to climb the learning curve

encoding: UTF-8

url: http://madsboending.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   facebook: mads.boending
   email: mads_boending@hotmail.com
   twitter:@MadsBnding

google_analytics: ""
